apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eci-api-ingress
  namespace: eci
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: api.eci.local
      http:
        paths:
          - path: /v1/products
            pathType: Prefix
            backend:
              service:
                name: catalog-service
                port:
                  number: 8080
          - path: /v1/orders
            pathType: Prefix
            backend:
              service:
                name: orders-service
                port:
                  number: 8082
          - path: /v1/inventory
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  number: 8081
          - path: /v1/payments
            pathType: Prefix
            backend:
              service:
                name: payments-service
                port:
                  number: 8083
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: catalog-service
                port:
                  number: 8080

